import { createStitches } from '@stitches/react'
import { mint, mintDark, gray, grayDark, whiteA, blackA } from '@radix-ui/colors'

export const stitches = createStitches({
  theme: {
    fonts: {
      system: 'system-ui',
      sans: '"Albert Sans", sans-serif',
      title: '"Unbounded VF", sans-serif',
      mono: 'Fira Mono, monospace',
      AktivGrotesk: 'aktiv-grotesk, sans-serif',
      AktivGroteskThin: 'aktiv-grotesk-thin, sans-serif',
    },
    colors: {
      ...mintDark,
      ...grayDark,
      ...whiteA,
      ...blackA,
      background: '$mint3',
      contentBackground: '$mint1',
      footerlink: '$whiteA8',
      link: '$mint12',
      title: '$mint12',
      description: 'rgb(231 252 247 / 70%)',
      content: 'rgb(231 252 247 / 60%)',
      modalBackground: '$mint3',
      menu: '$mint12',
      highlight: '$whiteA12',
      highlightText: '$mint10',
      highlightHover: '$mint3',
      highlightActiveBorder: 'rgba(255, 255, 255, 0.04)',
      tabBackground: 'rgba(255, 255, 255, 0.08)',
      tabText: 'rgba(255, 255, 255, 0.372)',
      linkContainerBackground: 'rgb(21, 21, 21)',
      linkContainerBorder: 'rgb(26, 26, 26)',
      linkContainerBackgroundHover: 'rgb(42, 42, 42)',
      linkContainerBorderHover: 'rgb(45, 45, 45)',
      overlayDarkness: 'rgba(0 0 0 / 0.65)',
      gradientButton: 'rgb(67, 231, 253)',
      twitter: '#0fa2f5',
    },
    fontSizes: {
      0: '10px',
      1: '12px',
      2: '14px',
      3: '18px',
      4: '20px',
      5: '24px',
      6: '32px',
    },
    fontWeights: {
      1: '300',
      2: '400',
      3: '500',
      4: '600',
      5: '700',
      6: '800',
    },
    lineHeights: {
      0: '1',
      1: '1.6',
      2: '1.8',
      3: '2.4',
      4: '3',
      5: '3.6',
      6: '4.8',
    },
    space: {
      1: '4px',
      2: '8px',
      3: '16px',
      4: '32px',
      5: '64px',
      6: '128px',
    },
    sizes: {
      1: '4px',
      2: '8px',
      3: '16px',
      4: '32px',
      5: '64px',
      6: '128px',
    },
    radii: {
      1: '2px',
      2: '4px',
      3: '6px',
      4: '8px',
      5: '16px',
      6: '32px',
      round: '9999px',
    },
    letterSpacings: {},
    borderWidths: {},
    borderStyles: {},
    shadows: {
      ...mintDark,
      ...whiteA,
      lightShadow: '$whiteA11',
      mint: '$mint11',
    },
    zIndices: {},
    transitions: {},
    // media: {
    //   bp1: '(min-width: 575px)',
    //   bp2: '(min-width: 750px)',
    //   bp3: '(min-width: 1000px)',
    //   bp4: '(min-width: 1200px)',
    // },
  }
})

// const lightTheme = theme({
//   colors: {
//     ...mint,
//     ...blackA,
//     background: '$mint3',
//     footerlink: '$blackA8',
//     link: '$mint12',
//     highlight: '$blackA12',
//   },
// })

export const { css, styled, globalCss, keyframes, getCssText, theme } = stitches
